import { combineReducers } from 'redux';
import { persistReducer } from 'redux-persist';
import storage from 'redux-persist/lib/storage'; //--> local storage location path generated by redux-persist

//--> all reducers are importted
import userReducer from './user/user.reducer';
import cartReducer from './cart/cart.reducer';
import directoryReducer from './directory/directory.reducer';
import shopReducer from './shop/shop.reducer';

//--> configuring which  reducer to track
const persistConfig = {
	key: 'root',
	storage,
	whitelist: ['cart'], //--> here it's the cart reducer
};

//--> typical :)
const rootReducer = combineReducers({
	user: userReducer,
	cart: cartReducer,
	directory: directoryReducer,
	shop: shopReducer,
});

export default persistReducer(persistConfig, rootReducer);
